// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAHuY3WPpPaIm3SYBFnqh_1zrhy3SlP_-0',
//     appId: '1:913474830081:web:4801b1c846600db7da2500',
//     messagingSenderId: '913474830081',
//     projectId: 'all-in-one-6c282',
//     authDomain: 'all-in-one-6c282.firebaseapp.com',
//     storageBucket: 'all-in-one-6c282.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDrfH-zEoe4ITx8S_rAPUkBb6VwzTkQaU0',
//     appId: '1:913474830081:android:b059703d99d95057da2500',
//     messagingSenderId: '913474830081',
//     projectId: 'all-in-one-6c282',
//     storageBucket: 'all-in-one-6c282.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCg74BfwcbNkN4H4mS7sYvR9tU091WVtw8',
//     appId: '1:913474830081:ios:921a82fe8cfaacc6da2500',
//     messagingSenderId: '913474830081',
//     projectId: 'all-in-one-6c282',
//     storageBucket: 'all-in-one-6c282.appspot.com',
//     iosBundleId: 'com.app.allInOne',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCg74BfwcbNkN4H4mS7sYvR9tU091WVtw8',
//     appId: '1:913474830081:ios:921a82fe8cfaacc6da2500',
//     messagingSenderId: '913474830081',
//     projectId: 'all-in-one-6c282',
//     storageBucket: 'all-in-one-6c282.appspot.com',
//     iosBundleId: 'com.app.allInOne',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAHuY3WPpPaIm3SYBFnqh_1zrhy3SlP_-0',
//     appId: '1:913474830081:web:afaeaf26557ac0a6da2500',
//     messagingSenderId: '913474830081',
//     projectId: 'all-in-one-6c282',
//     authDomain: 'all-in-one-6c282.firebaseapp.com',
//     storageBucket: 'all-in-one-6c282.appspot.com',
//   );
// }
